### ISSUE TITLE
proper releases

### ISSUE THREAD

**Issue by boegel** [naftaliharris/tauthon#104]
Are there any plans to make proper releases of Tauthon available sometime soon?

Just a tag on GitHub with a particular version be sufficient imho...

**Comment by stef** [comment]
i would like to package this for a distro, but our policy says we can only package proper versions, not random git checkouts. of course i could clone and make my own release, but that is a rather ugly workaround. so if it is possible, please make a release. i'll thank you with an alpine linux package.

**Comment by stefantalpalaru** [comment]
I propose we set PY_RELEASE_LEVEL to PY_RELEASE_LEVEL_FINAL and tag "2.8.0".

We need to decide on whether we'll update "Misc/NEWS.d" going forward: https://devguide.python.org/committing/#what-s-new-and-news-entries

We have 3 news items in the "next" subdir that need to be processed and deleted before the release.

**Comment by naftaliharris** [comment]
Guys, I'm really sorry for the delay here.  Am running a startup full time and super overworked.  Don't want to stand in your way.  Would somebody be willing to step up as owner/maintainer/etc for this project?

**Comment by naftaliharris** [comment]
😭

**Comment by vandys** [comment]
Just kicking off a startup here too, but... I'm using Tauthon for all the server code, including
my PEP572 stuff.  So, um, wouldn't say "no".

**Comment by stefantalpalaru** [comment]
I'm also available for project maintenance.

**Comment by vandys** [comment]
Naftali, since I'm in the same boat as you, Stefan is probably a better choice.  Thanks!

**Comment by naftaliharris** [comment]
Sounds great, @stefantalpalaru it is then!  What's the best way for us to do this?

Thanks a ton guys, means a lot to me.

**Comment by stefantalpalaru** [comment]
I'm already a collaborator with write access to this project. What I'm missing is a way to configure AppVeyor in order to fix the Windows CI build.

**Comment by naftaliharris** [comment]
@stefantalpalaru sent you an invite to your yahoo email address that adds you as an admin.  Let me know if that works!  If not perhaps I can remove appveyor from this project and you can set up one under your own name/account?

**Comment by stefantalpalaru** [comment]
Thanks, that did the trick! I've configured AppVeyor and now the Windows CI works as expected: https://ci.appveyor.com/project/naftaliharris/tauthon/builds/22600894

I'll make a release as soon as I fill in the missing parts of "Misc/NEWS.d/2.8.0.rst".

**Comment by naftaliharris** [comment]
You're an angel @stefantalpalaru. 🥇 🙇 🙏

**Comment by stefantalpalaru** [comment]
2.8.0 released: https://github.com/naftaliharris/tauthon/releases/tag/v2.8.0
