### ISSUE TITLE
be present on travis

### ISSUE THREAD

**Issue by graingert** [naftaliharris/tauthon#111]
Submit source to

https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build

so that projects can test with tauthon easily

**Comment by graingert** [comment]
@naftaliharris ok so the pyenv maintainer is ideologically opposed to tauthon 🤷

**Comment by naftaliharris** [comment]
Well, thanks for trying! cc @stefantalpalaru

**Comment by graingert** [comment]
Perhaps it's worth maintaining a fork of pyenv specifically for tauthon?
Then we can try to get Travis to use that fork?

**Comment by stefantalpalaru** [comment]
> Then we can try to get Travis to use that fork?

That's a very hard sell. It would be easier to write a shell script that can be downloaded and executed to install Tauthon on a Travis CI VM. Bonus points if it handles caching properly.

I've been using this strategy successfully with other projects:

https://github.com/status-im/nimbus/blob/devel/build_nim.sh is used in many other repos like this - https://github.com/status-im/nim-beacon-chain/blob/6704749eb04e9f81dfc125ecdee04ba4300aaaa9/.travis.yml#L29

and it's trivial to also use in AppVeyor: https://github.com/status-im/nim-beacon-chain/blob/6704749eb04e9f81dfc125ecdee04ba4300aaaa9/.appveyor.yml#L60

Same for https://github.com/status-im/nimbus/blob/devel/build_rocksdb.sh and the newer https://github.com/status-im/nim-beacon-chain/blob/a7d442e8f48ada077a6d7979b4ea471a13a3e7f6/scripts/process_lfs.sh

**Comment by stefantalpalaru** [comment]
This will be handled more realistically by providing binary packages, a matter tracked in this other issue: https://github.com/naftaliharris/tauthon/issues/71
