### ISSUE TITLE
C preprocessor symbol when building C extension modules for Tauthon?

### ISSUE THREAD

**Issue by dan-stromberg** [naftaliharris/tauthon#115]
Is there a cpp symbol I can #ifdef on when building for Tauthon?

I'm attempting to get subprocess32 going on Tauthon; it required removing a single function that was prototyped slightly differently (PyUnicode_FSConverter specifically).

**Comment by stefantalpalaru** [comment]
Can you use PY_VERSION_HEX? https://github.com/naftaliharris/tauthon/blob/08e1488e4bf1e58eb88c534ade8424ef3f72291b/Include/patchlevel.h#L39

**Comment by dan-stromberg** [comment]
Probably.  Thank you.

**Comment by dan-stromberg** [comment]
It turns out the subprocess32 maintainer (?) doesn't want a tauthon fix.  :(
