### ISSUE TITLE
Build a wheel for Tauthon?

### ISSUE THREAD

**Issue by dan-stromberg** [naftaliharris/tauthon#116]
I'm attempting to build and install a tauthon, binary, linux wheel for https://github.com/numenta/nupic.core , to be used inside a container, rather than building it inside the (minimalist) container every time the container is initialized.

I came up with a small set of patches to pip and wheel that enable this, but I suspect these changes have already been made to the upstream code and simply hasn't made it to the production releases of pip and wheel yet.  Otherwise, how is it that numpy is already available?

Is this the case?  I hope there's been no resistance to adding Tauthon support to pip and wheel.

What pep425 tag is Tauthon going with?  I arbitrarily used 'ta', but I'm more than open to switching to something else if it's the direction Tauthon is heading.

Thanks!

**Comment by stefantalpalaru** [comment]
> What pep425 tag is Tauthon going with? I arbitrarily used 'ta'

How about "ta28"?

**Comment by stefantalpalaru** [comment]
OK. That looks fine.

**Comment by dan-stromberg** [comment]
It sounds like not-quite-this, but something roughly equivalent, is happening:
https://github.com/pypa/packaging/issues/193
https://github.com/pypa/pip/issues/6908

^_^

**Comment by stefantalpalaru** [comment]
Solved by both Pip and Tauthon supporting PEP 421 and the creation of this external Virtualenv plugin: https://github.com/stefantalpalaru/virtualenv-tauthon
