### ISSUE TITLE
like 10000 errors

### ISSUE THREAD

**Issue by ufoul** [naftaliharris/tauthon#130]
I did ./configure then make on cygwin and it errored the shit out of me what the fuck it also didn't compile WOOOOOOOOOOOOOOOOOOOW

**Comment by stefantalpalaru** [comment]
This is not the right venue for being childish and self-centred. Post relevant output and instructions for reproducing the problem, not your unique reactions.

**Comment by cemeyer** [comment]
Not worth spending limited resources on trolls, IMO.
