### ISSUE TITLE
Fix security issues reported on bpo up to 2021/03/31

### ISSUE THREAD

**Issue by OlCe2** [naftaliharris/tauthon#138]
Hi,

I've gathered and fixed all security issues reported on bugs.python.org down to "normal" level up to 2021/03/31, sometimes by rolling out my own patches (especially for issues not yet fixed upstream) and the rest of the time by cherry-picking upstream commits (sometimes with several changes to make them and the associated test work).

I tested manually that the issues were indeed fixed (might have missed one or two), and all tests affected (and news ones imported) seem to pass. The only thing I didn't is the update of OpenSSL in CI, Mac and Windows build scripts, which I don't use, so please especially review that.

Following request was used:
https://bugs.python.org/issue?%40search_text=&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=&nosy=&type=4&components=&versions=&dependencies=&assignee=&keywords=&priority=&%40columns=priority&%40group=priority&status=&%40columns=status&resolution=&nosy_count=&message_count=&%40pagesize=500&%40startwith=0&%40sortdir=on&%40action=search
See also:
https://python-security.readthedocs.io/

I focused on issues with severity down to normal (and issues without assigned severity), and hopefully all of them  that were not included in Python 2.7 (for this, I went back for at least a year, and much more in the case of blocker or critical issues).

The full list of issues considered as well as the actions I took for each is available in the attached file (apparently, I cannot attach it right now, will do short after creation).

I've locally made modifications to build Tauthon 2.8.3a1 and test. I would be great to have such an alpha release of Tauthon so that people can test all these changes in their use-cases (once you've also merged PR #137). Also, please wait before issuing a final release, because [bpo-43124](https://bugs.python.org/issue43124) is going to get a fix we may consider to import, having been marked release blocker (although, arguably, this problem is not so "important").

**Comment by OlCe2** [comment]
Here is the file listing issues and actions:
[python_issues.txt](https://github.com/naftaliharris/tauthon/files/6244346/python_issues.txt)

**Comment by OlCe2** [comment]
The PR #139 does not include the update to OpenSSL 1.1.1k, since the imports have tried lead to compile errors. I think this may be solved by importing more project files, but I won't have time to test that until next week.

In the meantime, if you know how to do it, please go ahead.

**Comment by OlCe2** [comment]
Did you have time to review the MR?

I don't think we should wait for [bpo-43124](https://bugs.python.org/issue43124) to be resolved. It was flagged initially with normal priority, then made blocker but downgraded to deferred-blocker, with absolutely no sign of any activity.

As for the upgrade to OpenSSL 1.1.1k in the Windows build, didn't have time to work on it, and not sure I'll have time for the next two weeks. Can be dealt with in a separate issue, in order not to block this one.

Thanks.

**Comment by stefantalpalaru** [comment]
I want to set up GitHub Actions first, and see all these changes pass CI: https://github.com/naftaliharris/tauthon/pull/140

Since Travis became unusable, all we're left with is AppVeyor and that's not enough.

All works in GitHub Actions except Windows, where I wanted to support a newer Visual Studio version instead of the long-deprecated one we use in AppVeyor. That part is harder than expected.

**Comment by OlCe2** [comment]
Yes, a single CI is not enough. Just out of curiosity, do you know why Travis became unusable?

And yes, supporting a more recent Visual Studio would be great (e.g., we could use some C99).

**Comment by stefantalpalaru** [comment]
> do you know why Travis became unusable?

New owners killing it in an attempt to make it profitable: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by stefantalpalaru** [comment]
PR merged.
