### ISSUE TITLE
Question about compilation for spidermonkey

### ISSUE THREAD

**Issue by throgh** [naftaliharris/tauthon#143]
Hello together,

we from Hyperbola GNU/Linux-libre have integrated Tauthon as our major alternative for Python 2. But I as packager have now some issues to build 0ad in version 0.0.23.1: The problem is the component spidermonkey being part of the compilation-process and demands python2. I get the following error:

`ImportError: No module named _oserror
ERROR: The executable /home/.../0ad/src/0ad-0.0.23b-alpha/libraries/source/spidermonkey/mozjs-38.0.0/js/src/build-debug/_virtualenv/bin/tauthon2.8 is not functioning`

More details:

`ERROR: virtualenv is not compatible with this system or executable
Traceback (most recent call last):
  File "/home/.../0ad/src/0ad-0.0.23b-alpha/libraries/source/spidermonkey/mozjs-38.0.0/python/mozbuild/mozbuild/virtualenv.py", line 475, in <module>
    manager.ensure()
  File "/home/.../0ad/src/0ad-0.0.23b-alpha/libraries/source/spidermonkey/mozjs-38.0.0/python/mozbuild/mozbuild/virtualenv.py", line 128, in ensure
    return self.build()
  File "/home/.../0ad/src/0ad-0.0.23b-alpha/libraries/source/spidermonkey/mozjs-38.0.0/python/mozbuild/mozbuild/virtualenv.py", line 371, in build
    self.create()
  File "/home/.../0ad/src/0ad-0.0.23b-alpha/libraries/source/spidermonkey/mozjs-38.0.0/python/mozbuild/mozbuild/virtualenv.py", line 147, in create
    raise Exception('Error creating virtualenv.')`

Perhaps you have some hints for me where to look and fix this problem?
Thank you!

**Comment by vandys** [comment]
If you just start up tauthon and "import _oserror", does that fail?  That's a plain old module in your tauthon install's library directory.  That appears to be the complaint, but something has to be pretty wrong if it's missing.  Perhaps an incomplete install to your virtualenv?  (virtualenv's are not something I have any familiarity with, sorry!)

**Comment by throgh** [comment]
Hey, thanks for the first hint onto this. Starting up plain tauthon and executing the line "import _oserror" seems to work out of the box (no further error to be recognized). Especially the second part could be a possible solution, but I have also not that much experience within virtualenv. Nevertheless: Much appreciated for your feedback!

Another note therefore: As we use pacman (or better hyperman as fork) for our packages we have therefore compatible syntax from Arch Linux to follow. I have tried to remove all references towards python2 with:

`  find "$srcdir/$pkgname-$_pkgver/libraries/source/spidermonkey/" \( -type d -name .git -prune \) -o -type f -print0 |
    xargs -0 sed -i 's/env python/env tauthon/g'

  # now get tauthon in the place
  cd "$srcdir/$pkgname-$_pkgver/"
  find . -type f -exec sed -i 's/python2[.]7/tauthon2.8/g' {} +
  find . -type f -exec sed -i 's/python2/tauthon/g' {} +`

But I'm unsure if this is even enough!

**Comment by vandys** [comment]
When replacing "python2" path element, make sure there's a plain "tauthon" path element.  On my install, there's no /usr/local/lib/tauthon, nor .../tauthon2, only .../tauthon2.8.

You may need to slip an strace in there to see where it's looking for that missing _oserror.

Good luck!

**Comment by throgh** [comment]
Okay, will go further into this and give further feedback after research.
Thank you!

**Comment by OlCe2** [comment]
Hi @throgh ,

You may want to look I what I did for the Palemoon browser. Since their repository are private now, I attached a git diff.

[pm_diff.txt](https://github.com/naftaliharris/tauthon/files/8004212/pm_diff.txt)

I don't know how much their build system, initially based on Firefox's, drifted, but this should at least give you ideas about what to patch.

Regards.

**Comment by stefantalpalaru** [comment]
> ImportError: No module named _oserror

It was a Virtualenv problem - a missing symlink to "_oserror.py" next to the one to "os.py". Solved by this externel Virtualenv plugin: https://github.com/stefantalpalaru/virtualenv-tauthon
