### ISSUE TITLE
Is it still developed?

### ISSUE THREAD

**Issue by 3oheicrw** [naftaliharris/tauthon#144]
Last commits were from 2021.

**Comment by vandys** [comment]
I would like for it to be!  At this point, I think an important part is to provide easily populated dist-packages in support of Tauthon installs.  I have assembled my own cache of such packages, for instance.

**Comment by 3oheicrw** [comment]
I want the answer from the developers. So far no one cares. It's very likely this project is dead.

**Comment by stefantalpalaru** [comment]
> I want the answer from the developers. So far no one cares. It's very likely this project is dead.

Or you could help, instead of complaining.

**Comment by 3oheicrw** [comment]
> > I want the answer from the developers. So far no one cares. It's very likely this project is dead.
> 
> Or you could help, instead of complaining.

No. I don't have that ability. I only want to know if this project is still developed. The answer seems to be no.

**Comment by stefantalpalaru** [comment]
> I only want to know if this project is still developed.

No, you don't.

> The answer seems to be no.

*Errare humanum est, perseverare diabolicum.*

https://github.com/naftaliharris/tauthon/pull/146

https://github.com/naftaliharris/tauthon/pull/145

**Comment by 3oheicrw** [comment]
> > I only want to know if this project is still developed.
> 
> No, you don't.
> 
> > The answer seems to be no.
> 
> _Errare humanum est, perseverare diabolicum._
> 
> #146
> 
> #145

No. I want the answer from the repo owner aka. the project owner. Not you, isn't it? You are only a collaborator. So far he didn't care. He didn't step up to make even a single statement regarding the state of his project. It's nothing wrong for me to think it's abandoned. There is almost no issues submitted during the recent two years. I checked all of the branches. This project doesn't use branches much. Commits are directly to the master branch. Other branches are from many years ago and all outdated. BTW, I'm not a westerner. I don't understand nor I want to understand your Latin.

**Comment by stefantalpalaru** [comment]
> I want the answer from the repo owner aka. the project owner. Not you, isn't it? You are only a collaborator.

I'm the project maintainer.

>  It's nothing wrong for me to think it's abandoned.

You think what you want, little buddy.

> I don't understand nor I want to understand your Latin.

*Mediocritas optima est.*

**Comment by cemeyer** [comment]
I suggest banning the troll and locking the thread.

**Comment by stefantalpalaru** [comment]
> I suggest banning the troll and locking the thread.

Bit harsh. He did inspire me to work on Tauthon these last few days, so I'll cut him some slack ;-)

**Comment by vandys** [comment]
> > I want the answer from the repo owner aka. the project owner. Not you, isn't it? You are only a collaborator.
> 
> I'm the project maintainer.
> 
> > It's nothing wrong for me to think it's abandoned.
> 
> You think what you want, little buddy.
> 
> > I don't understand nor I want to understand your Latin.
> 
> _Mediocritas optima est._

ROTFL! :)

**Comment by vandys** [comment]
> > I suggest banning the troll and locking the thread.
> 
> Bit harsh. He did inspire me to work on Tauthon these last few days, so I'll cut him some slack ;-)

I did a ton of work on := (and made += and friends also expression-capable).  it was all good, except it failed in the automated tests on MacOS.  I eventually even got a Mac--and couldn't reproduce it!

It's suffered some bit rot, but I could pick it back up if somebody can let me gdb into a Mac which reproduces the issue?

--Andy

**Comment by stefantalpalaru** [comment]
> I eventually even got a Mac

BTW, I do my local macOS testing on an old VMware image (Sierra 10.12.5) hacked to run on AMD processors.

> couldn't reproduce it!

There's always print debugging in GitHub Actions, and your own repo fork might run those CI jobs faster. You can even disable the Linux jobs while you debug it.

**Comment by 3oheicrw** [comment]
> > I suggest banning the troll and locking the thread.
> 
> Bit harsh. He did inspire me to work on Tauthon these last few days, so I'll cut him some slack ;-)

Believe me or not, I'm actually glad when know this project is still kicking. I did advertised it to many still have Python2 scripts not yet migrated to Python3. If this project suddenly dies then I will be a joke in their eyes.

**Comment by 3oheicrw** [comment]
I think this issue should be open for others could know the status of the project.

**Comment by stefantalpalaru** [comment]
No, that's not how issues work.

**Comment by 3oheicrw** [comment]
> No, that's not how issues work.

Feel free to have new people come and open similar issue like this. You have no discussion forum so this issue section is the only way to contact you. You should at least add the current state of the project to readme so other will not waste time opening similar issue. BTW, it seems you can't stop being hostile to me. It's your project, maintain it good, I will never recommend it to anyone again. Bye.

**Comment by vandys** [comment]
Sheesh, I've heard about github trolls, but this is the first one I've seen in the wild.  Let's move on, unless the unbearable weight of not being recommended by a rando has devastated you.  ;-)

**Comment by 3oheicrw** [comment]
> Sheesh, I've heard about github trolls, but this is the first one I've seen in the wild. Let's move on, unless the unbearable weight of not being recommended by a rando has devastated you. ;-)

I forgot to unsubscribe from this and received notification about this reply. People here is unable to descern between what is a troll and what is a sincere question. But it's OK. I was never considered to be a troll on any github project, only this. I don't care about what you think. Keep this POS for your own toxic community use. Never see again.
