### ISSUE TITLE
Undo the changes to int(...), float(...), etc.

### ISSUE THREAD

**Issue by naftaliharris** [naftaliharris/tauthon#22]
People may depend on the behavior of these when parsing data input.

**Comment by proteasome** [comment]
can you supply or point to examples?   other than int vs long, float rounding, input vs raw_input, i don't se ant differences between 2.6+ and 3.5+ concernint int() itself

**Comment by naftaliharris** [comment]
Yeah, for example

```python
>>> int("1_200")
```

This will raise a ValueError in Python 2 and 3.5-, but in Python 3.6 and in tauthon it will parse as it into the int `1200`.

More info here: https://www.python.org/dev/peps/pep-0515/

The concern is that someone might have code that relies on `int` or `float` throwing a ValueError in these cases, and now we're returning actual values here. E.g., if you made a json parser using the `int` builtin, it would now parse non-json as json if you upgraded from 2.7 to tauthon. (The standard lib json checks explicitly that input matches the json spec, if I recall correctly).

**Comment by naftaliharris** [comment]
Having underscores in numeric literals is actually one of my favorite features in tauthon. It's a lot easier to see that

```python
BILLION = 1_000_000_000
```

actually is one billion, rather than

```python
BILLION = 1000000000
```

**Comment by proteasome** [comment]
thx.  this begs the q of whether 3.x features could be selectively dis/enabled dynamically during runtime, or more simply, at startup by tauthon cli switches, or env vars.   least preferable, imho, would be to do feature granularity at build time, tho some shops would undoubtably find that useful. for tauthon's adoption that would be a very powerful draw, as developers could more easily test 2/3 compatibility by toggling features.  i'll open a new issue on this, if you don't mind.

**Comment by naftaliharris** [comment]
> this begs the q of whether 3.x features could be selectively dis/enabled dynamically during runtime, or more simply, at startup by tauthon cli switches, or env vars.

I'm personally -1 on the ability to toggle different features, mostly because of how difficult it would be to implement, test, and maintain.

Toggling run-time switches would be the most challenging, though doing it at build time would be pretty hard as well. The reason is that adding a new language feature involves updating Python's grammar file (Grammar/Grammar), which leads to a ton of generated tokenizing and parsing code in e.g. Python/graminit.c, and then requires updates to the AST and compiler. So to toggle this at runtime or even build time, you'd presumably need a bunch of different copies of the tokenizing, parsing, and compiling code.

With n different binary features, possibly as many as 2^n different copies, since many of the features aren't "independent" of each other. For example, function annotations, async/await syntax, and keyword only arguments all touch the grammar related to functions, so it isn't trivial to pick a subset of them that you want to include without having special code for all 8 possible subsets.

**Comment by proteasome** [comment]
i agree let's make it -2 on the toggles (and not open an issue) it would be different if python 2 or 3 already had that sort of self knowledge built in.   it's also not clear that there would enough use of this feature in the field.

**Comment by naftaliharris** [comment]
@proteasome if you're interested, some details about what's involved with making a language change: https://www.naftaliharris.com/blog/nonlocal/

**Comment by proteasome** [comment]
thx.  looks good.

**Comment by vandys** [comment]
I, too, would prefer the enhanced numeric format support.  And would also prefer to *not* have
the combinatoric mesh of feature switches.  Pick a good answer, and run with it (which you already
have)!

**Comment by arizvisa** [comment]
Instead of toggling (or some other means) that requires modification of tauthon, it might be possible to disable some of these features using a module that just monkey-patches the functionality used by the application that depends on these capability. `int` is a simple example to change because you could just search for underscores and then raise your `ValueError`.

`$ tauthon -m downgrade -opt1 -opt2 -opt3 whatever.py`

Then `downgrade.py` could tamper with whatever namespace the callable resides in before using `execfile` on `whatever.py`.

**Comment by stefantalpalaru** [comment]
We want to guarantee that valid Python2 code runs in Tauthon, not that invalid Python2 code doesn't run.
