### ISSUE TITLE
tauthon to replace python2.8 on startup banner

### ISSUE THREAD

**Issue by proteasome** [naftaliharris/tauthon#65]
└─╼ ./tauthon.exe 
Python 2.8.0a0 (default, Feb 23 2017, 16:57:01) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

seems that Python 2.8.0a0. should be tauthon2.8.0a0 ?

running on OS X

**Comment by naftaliharris** [comment]
Ha, I actually just fixed this this afternoon, in #64. Thanks though!

**Comment by naftaliharris** [comment]
Right here: https://github.com/naftaliharris/tauthon/pull/64/commits/84b135dac34929bfce226440c821ca58357c6ed9#diff-75445bdc3b6b3dd20b005698fa165444R550
