### ISSUE TITLE
tauthon help() refers to python 2.8

### ISSUE THREAD

**Issue by proteasome** [naftaliharris/tauthon#66]
└─╼ ./tauthon.exe 
Tauthon 2.8.0a0 (default, Feb 24 2017, 00:03:02) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> help()

Welcome to Python 2.8!  This is the online help utility.

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at http://docs.python.org/2.8/tutorial/.

========

looks like it's coming from here in pydoc

grep -n Welcome tauthon-master/Lib/pydoc.py
1859:Welcome to Python %s!  This is the online help utility.

grep -n Internet tauthon-master/Lib/pydoc.py
1862:the tutorial on the Internet at http://docs.python.org/%s/tutorial/.

**Comment by naftaliharris** [comment]
> Welcome to Python 2.8! This is the online help utility.

Easy enough to fix; s/Python/Tauthon

Just remove the reference to the tutorial, you think? I actually own tauthon.org; would love to put something up there eventually.

**Comment by proteasome** [comment]
yep.  makes sense.  there could be a "tauthon" tutorial which will point to the latest 2.7.x (and after EOL, the last 2.7) and whatever makes sense from 3.x, and adds info about the edge cases
