### ISSUE TITLE
Build tauthon on Windows

### ISSUE THREAD

**Issue by naftaliharris** [naftaliharris/tauthon#69]

**Comment by naftaliharris** [comment]
@kovidgoyal

**Comment by naftaliharris** [comment]
@kovidgoyal, do you know what the error is here? https://ci.appveyor.com/project/naftaliharris/tauthon

I tried to follow your cpython fork, based my .appveyor.yml off of that.

**Comment by naftaliharris** [comment]
appveyor file is here: https://github.com/naftaliharris/tauthon/blob/bfd4d6b156cbd707c92d67e8e1ce12c19263a98f/.appveyor.yml

**Comment by kovidgoyal** [comment]
I'm not going to be able to get to this for a day or two, I'll follow up after that.

**Comment by kovidgoyal** [comment]
I had a quick look on my phone. IIRC VS 2008 Express Edition which is what appveyor uses does not support building 64bit -- you need to use VS 2008 Pro for that.

**Comment by naftaliharris** [comment]
Cool, I'm trying again with x86 instead of x64!

**Comment by kovidgoyal** [comment]
I see that now appveyor is giving the error Build worker image not found: Visual Studio 2008

Here is an example python project that works with VS 2008 on appveyor: 
https://ci.appveyor.com/project/ogrisel/python-appveyor-demo

It has both 32 and 64 bit builds, so you should probably setup your appveyor file based on that.

**Comment by kovidgoyal** [comment]
And you probably need to add VS 2008 explicitly in your appveyor account, as discussed here: https://github.com/appveyor/ci/issues/1197

**Comment by stefantalpalaru** [comment]
Solved at some point in the past.
