### ISSUE TITLE
itauthon needed as either an ipython or isympy analog?

### ISSUE THREAD

**Issue by proteasome** [naftaliharris/tauthon#74]
not sure if itauthon is needed - it could be the analog of ipython, or it could be a wrapper like isympy which does a few helpful things for sympy by pre-populating.

"""
ipython:

if __name__ == '__main__':
    import sys
    import IPython

    sys.exit(IPython.start_ipython())
"""

"""
└─╼ isympy -h
Python shell for SymPy.

This is just a normal Python shell (IPython shell if you have the
IPython package installed), that executes the following commands for
the user:

    >>> from __future__ import division
    >>> from sympy import *
    >>> x, y, z, t = symbols('x y z t')
    >>> k, m, n = symbols('k m n', integer=True)
    >>> f, g, h = symbols('f g h', cls=Function)
    >>> init_printing()
"""

**Comment by stefantalpalaru** [comment]
IPython 5.x works out of the box inside a [Virtualenv environment](https://github.com/stefantalpalaru/virtualenv-tauthon):

```text
pip install ipykernel pathlib2
$ ipython
/src/77_DLD/CODE/00_github/virtualenv/venv/lib64/tauthon2.8/site-packages/IPython/core/history.py:228: UserWarning: IPython History requires SQLite, your history will not be saved
  warn("IPython History requires SQLite, your history will not be saved")
Python 2.8.3 (default, Dec  6 2022, 09:54:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.10.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sys

In [2]: print sys.base_executable, sys.version
/usr/bin/tauthon2.8 2.8.3 (default, Dec  6 2022, 09:54:06) 
[GCC 12.2.1 20221008]
```

So it claims to use "Python 2.8.3", but it's actually Tauthon.
