### ISSUE TITLE
man page for tauthon

### ISSUE THREAD

**Issue by proteasome** [naftaliharris/tauthon#76]
OSX 10.12.3 (Sierra) 
"""
$ make install | grep man | egrep -v 'command|roman|manager'
...
/usr/bin/install -c -m 644 ./Misc/python.man \
		/usr/local/share/man/man1/python2.8.1
rm -f /usr/local/share/man/man1/python2.1
(cd /usr/local/share/man/man1; ln -s python2.8.1 python2.1)
rm -f /usr/local/share/man/man1/python.1
(cd /usr/local/share/man/man1; ln -s python2.1 python.1)
"""

"""
└─╼ man -w python2.8
/usr/local/share/man/man1/python2.8.1
"""

"""man python2.8

PYTHON(1)                                                            PYTHON(1)

NAME
       python  - an interpreted, interactive, object-oriented programming lan-
       guage

SYNOPSIS
       python [ -B ] [ -d ] [ -E ] [ -h ] [ -i ] [ -m module-name ]
              [ -O ] [ -OO ] [ -R ] [ -Q argument ] [ -s ] [ -S ] [ -t ] [  -u
       ]
              [ -v ] [ -V ] [ -W argument ] [ -x ] [ -3 ] [ -?  ]
              [ -c command | script | - ] [ arguments ]

DESCRIPTION
       Python is an interpreted,
"""

if there will be tauthon man page, does it need to be tauthonized ?

**Comment by stefantalpalaru** [comment]
Man page renamed and edited accordingly in https://github.com/naftaliharris/tauthon/pull/89.
