### ISSUE TITLE
environment variables PYTHON vs TAUTHON

### ISSUE THREAD

**Issue by proteasome** [naftaliharris/tauthon#77]
OSX 10.12.3 (Sierra)

there are a number of env vars used by tauthon as shown by help:

>"""
└─╼ tauthon -h | egrep -i "PY|TAU" 
usage: tauthon [option] ... [-c cmd | -m mod | file | -] [arg] ...
-B     : don't write .py[co] files on import; also PYTHONDONTWRITEBYTECODE=x
-d     : debug output from parser; also PYTHONDEBUG=x
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
         if stdin does not appear to be a terminal; also PYTHONINSPECT=x
-O     : optimize generated bytecode slightly; also PYTHONOPTIMIZE=x
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE
-u     : unbuffered binary stdout and stderr; also PYTHONUNBUFFERED=x
-v     : verbose (trace import statements); also PYTHONVERBOSE=x
         also PYTHONWARNINGS=arg
PYTHONSTARTUP: file executed on interactive startup (no default)
PYTHONPATH   : ':'-separated list of directories prefixed to the
PYTHONHOME   : alternate <prefix> directory (or <prefix>:<exec_prefix>).
               The default module search path uses <prefix>/pythonX.X.
PYTHONCASEOK : ignore case in 'import' statements (Windows).
PYTHONIOENCODING: Encoding[:errors] used for stdin/stdout/stderr.
PYTHONHASHSEED: if this variable is set to 'random', the effect is the same
>"""

note: python3 supports all of these plus
>"""
PYTHONFAULTHANDLER: dump the Python traceback on fatal errors.
PYTHONMALLOC: set the Python memory allocators and/or install debug hooks
>"""

do any of these need TAUTHON analogs? if so, should the PYTHON one then be ignored?
is there a need to allow for different values for tauthon and python applications.

perhaps, for the time being it isn't necessary to do anything.

**Comment by torgil** [comment]
>> "is there a need to allow for different values for tauthon and python applications."

You can set these separately on each invocation without changing names. Otherwise you'd need a name per script.

**Comment by proteasome** [comment]
right.  some users might set these globally, tho.  even so, it seems fine to wait for a real life use case before creating TAUTHON variables.  certainly, the less special tweaking a tauthon user has to do, the better and after all, the point of tauthon is give the look and feel of python2 as much as possible.

**Comment by arizvisa** [comment]
Definitely a fan of not changing environment variables in order to remain compatible with Python2.

**Comment by stefantalpalaru** [comment]
Yeah, we're sticking with `PYTHON*` for Python2 compatibility.
