### ISSUE TITLE
pip should just work out of the box

### ISSUE THREAD

**Issue by torgil** [naftaliharris/tauthon#78]
The first thing you want to do after compiling / installing Tauthon is probably to install third party products like numpy and scipy. 

pip install [package]

This should just work out of the box.

**Comment by torgil** [comment]
This is what I had to do to get numpy going on Xubuntu 16.04:
```
$ export TAUTHON_PATH=/path/to/tauthon/build
$ sudo update-alternatives --install /usr/bin/tauthon tauthon $TAUTHON_PATH/tauthon 1
$ sudo update-alternatives --install /usr/bin/python python $TAUTHON_PATH/tauthon 1
$ sudo update-alternatives --install /usr/bin/python2.8 python2.8 $TAUTHON_PATH/tauthon 1
$ sudo ln -s $TAUTHON_PATH/tauthon /usr/local/bin/python2.8
$ cp $TAUTHON_PATH/pyconfig.h $TAUTHON_PATH/Include/
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo tauthon get-pip.py
$ sudo pip2.8 install --global-option=build_ext --global-option="-I$TAUTHON_PATH/Include" numpy
```

**Comment by auscompgeek** [comment]
[Tauthon has ensurepip](https://github.com/naftaliharris/tauthon/tree/master/Lib/ensurepip).

**Comment by arizvisa** [comment]
It seems like we can just put this in the wiki, right?

**Comment by stefantalpalaru** [comment]
It does work now, from inside a Virtualenv environment: https://github.com/stefantalpalaru/virtualenv-tauthon
