### ISSUE TITLE
Tauthon file extension

### ISSUE THREAD

**Issue by torgil** [naftaliharris/tauthon#79]
I'm about to create a Tauthon debugging environment (yes, after LOTS of consideration and experimentation, python3 was a lesser option due to various reasons I won't discuss here) and plan to add Tauthon specific features.

What are your stand on adding (library enhancements, not language) features not present in Python3, especially additions to libraries like ctypes?

My Tauthon scripts probably will not run on either python2.7 or python3 (regardless of any library enhancements). I think in that case I should have another file-extension to avoid confusion. What is your stance on this?  Is ".tau" something pretty we could live with (and ".py" only if backwards compatible with Python2.7) ?  :-)

**Comment by naftaliharris** [comment]
> What are your stand on adding (library enhancements, not language) features not present in Python3, especially additions to libraries like ctypes?

Opposed, I'm afraid. I'd like to keep this project pretty conservative.

> My Tauthon scripts probably will not run on either python2.7 or python3 (regardless of any library enhancements). I think in that case I should have another file-extension to avoid confusion. What is your stance on this? Is ".tau" something pretty we could live with (and ".py" only if backwards compatible with Python2.7) ? :-)

I'd be open to .tau. There's no difficulty having your main script be a .tau; you just run:

```
$ tauthon somescript.tau
```

More challenging is if you want to import modules with a ".tau" extension. I'd be open to making a change to allow this.

**Comment by torgil** [comment]
> Opposed, I'm afraid. I'd like to keep this project pretty conservative.

I planned to be completely backwards compatible. It'd be nice if we could make Tauthon "just works" in the same spirit as when python/numpy arrived, but of course the next level of it. Is "Tauthon 3" maybe a good point to get innovative? ;-) No worries, there are plenty of options to have features outside the core package and still work seamless.

> More challenging is if you want to import modules with a ".tau" extension. I'd be open to making a change to allow this.

Nice. This would make things more "official", I aim for the least confusion.

**Comment by proteasome** [comment]
.tau would be nice to have.

simple and conservative feels best considering tauthon's stated purpose and TBD community.

**Comment by stefantalpalaru** [comment]
Introducing a new file extension brings no benefits.
