### ISSUE TITLE
ffi_common.h and source code path

### ISSUE THREAD

**Issue by vandys** [naftaliharris/tauthon#95]
I had a funny one where my build of _ctype would fail with not finding ffi_common.h.
It turns out if you move your source tree, this compilation error will crop up until you
blow away all the files which record your absolute source path.  (On Debian, at least.)

I'm not sure this is something to be fixed, but I figured it might be nice to save somebody
else some minutes of time if they get bit by it.  Maybe start collecting lessons learned
in the wiki part of this project?

**Comment by stefantalpalaru** [comment]
It's not exaggerated to require a "make clean" after moving the source tree.

**Comment by vandys** [comment]
I actually thought I had... I'll experiment more when I have some time.  The funny part was how much actually worked.

**Comment by vandys** [comment]
Maybe this can join a "gotcha" someday
