### ISSUE TITLE
Regression test hang in test.test_concurrent_futures.ProcessPoolAsCompletedTests

### ISSUE THREAD

**Issue by vandys** [naftaliharris/tauthon#96]
When running test/testall on trunk, the last line in this output has the testing stopped.
Are we expecting this test suite to pass?

0:00:40 load avg: 0.41 [ 88/416] test_concurrent_futures
test_cancel (test.test_concurrent_futures.FutureTests) ... ok
test_cancelled (test.test_concurrent_futures.FutureTests) ... ok
test_done (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_already_cancelled (test.test_concurrent_futures.FutureTests)
... ok
test_done_callback_already_failed (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_already_successful (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_raises (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_with_cancel (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_with_exception (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_with_result (test.test_concurrent_futures.FutureTests) ... ok
test_exception_with_success (test.test_concurrent_futures.FutureTests) ... ok
test_exception_with_timeout (test.test_concurrent_futures.FutureTests) ... ok
test_repr (test.test_concurrent_futures.FutureTests) ... ok
test_result_with_cancel (test.test_concurrent_futures.FutureTests) ... ok
test_result_with_success (test.test_concurrent_futures.FutureTests) ... ok
test_result_with_timeout (test.test_concurrent_futures.FutureTests) ... ok
test_running (test.test_concurrent_futures.FutureTests) ... ok
test_duplicate_futures (test.test_concurrent_futures.ProcessPoolAsCompletedTests) ...

Processes at this point:
20187 pts/5    Sl+    0:30 ./tauthon
20354 pts/5    S+     0:00 ./tauthon
20355 pts/5    S+     0:00 ./tauthon
20356 pts/5    S+     0:00 ./tauthon
20357 pts/5    S+     0:00 ./tauthon
20358 pts/5    S+     0:00 ./tauthon

**Comment by stefantalpalaru** [comment]
Run the tests like this, to avoid using any file outside the project's tree:

```sh
make test TESTOPTS="-v test_concurrent_futures"
```
Is it still hanging?

**Comment by vandys** [comment]
Two thanks you's--it doesn't hang, and I learned a new make target to use.
