### ISSUE TITLE
Regression test test_multiprocessing fails

### ISSUE THREAD

**Issue by vandys** [naftaliharris/tauthon#97]
On trunk I see numerous tests from Lib/test/test_multiprocessing.py fail.
Basic complaint is that "bisect_left" is not in module "bisect" (which it is).

I'm going to climb down this rabbit hole because these tests are pretty nice in
their thoroughness... please post a comment if you know why these failures
are OK, thanks.

**Comment by stefantalpalaru** [comment]
Those tests are known to occasionally fail, on Tauthon as on Python: https://bugs.python.org/issue13059

Can you go back to your previous test-related issue and try the suggested command? https://github.com/naftaliharris/tauthon/issues/96

**Comment by vandys** [comment]
Ok, pulled 96 to front of queue and resolved.  I'm going to dig into this one some more since it looks a little
more reliably hosed than what they were talking about.  At least enough to get a feel for what
went wrong.

**Comment by stefantalpalaru** [comment]
Remember to use ```make test TESTOPTS="-v test_multiprocessing"``` to completely isolate the tests from modules outside the source tree.

**Comment by vandys** [comment]
Thanks, yes, path issue.  Note that: tauthon Lib/test/regrtest.py [-v] test_multiprocessing
suffices to run in the test environment.
